<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>

		<OutputPath>..\..\uWidgets\bin\$(Configuration)\$(TargetFramework)\Widgets</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.1.3" />
		<PackageReference Include="Microsoft.Playwright" Version="1.55.0" />
		<PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\uWidgets.Core\uWidgets.Core.csproj" />
	</ItemGroup>
	
</Project>
